#!/usr/bin/env python3

content = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus turpis in. Gravida quis blandit turpis cursus in hac habitasse platea. Eget aliquet nibh praesent tristique magna sit amet purus. Enim lobortis scelerisque fermentum dui faucibus in. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Aliquam etiam erat velit scelerisque in. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. In nibh mauris cursus mattis. Dignissim suspendisse in est ante in nibh. Rhoncus urna neque viverra justo nec ultrices. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Non nisi est sit amet facilisis. Morbi quis commodo odio aenean. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Dolor sit amet consectetur adipiscing elit. Vulputate sapien nec sagittis aliquam.

Diam ut venenatis tellus in metus. Mi proin sed libero enim sed faucibus turpis in eu. Enim ut tellus elementum sagittis vitae. Dignissim diam quis enim lobortis scelerisque. Mauris ultrices eros in cursus turpis massa tincidunt dui. Sed faucibus turpis in eu mi bibendum neque. Vestibulum mattis ullamcorper velit sed. Nec nam aliquam sem et tortor consequat id porta nibh. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Tristique nulla aliquet enim tortor at auctor urna.

Ipsum nunc aliquet bibendum enim facilisis. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Et malesuada fames ac turpis egestas sed tempus urna et. Tristique sollicitudin nibh sit amet commodo nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Libero id faucibus nisl tincidunt eget nullam. Nibh cras pulvinar mattis nunc. Interdum velit euismod in pellentesque massa placerat duis ultricies. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Vel pretium lectus quam id leo in vitae turpis. Ac tortor dignissim convallis aenean et tortor at risus viverra. Nisi scelerisque eu ultrices vitae auctor.

Massa sed elementum tempus egestas sed sed. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Tortor pretium viverra suspendisse potenti nullam ac. Proin sagittis nisl rhoncus mattis rhoncus urna. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Sed faucibus turpis in eu. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Nec ullamcorper sit amet risus nullam eget. Arcu cursus vitae congue mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Scelerisque mauris pellentesque pulvinar pellentesque. Sit amet tellus cras adipiscing enim eu turpis egestas. Eu ultrices vitae auctor eu.

Pulvinar elementum integer enim neque volutpat. Massa eget egestas purus viverra accumsan in nisl nisi. In fermentum et sollicitudin ac orci phasellus. Dolor magna eget est lorem ipsum dolor. Id cursus metus aliquam eleifend. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Pellentesque habitant morbi tristique senectus et netus et malesuada. Eget aliquet nibh praesent tristique. Ipsum dolor sit amet consectetur adipiscing elit ut. Sed id semper risus in hendrerit. Suspendisse sed nisi lacus sed viverra tellus in. Blandit massa enim nec dui nunc mattis enim ut. Massa enim nec dui nunc mattis enim ut tellus elementum.

Vitae nunc sed velit dignissim sodales ut eu. Ut placerat orci nulla pellentesque dignissim enim sit. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit. Nec dui nunc mattis enim. Et malesuada fames ac turpis egestas. Augue neque gravida in fermentum et sollicitudin ac orci. Bibendum ut tristique et egestas quis. Ut aliquam purus sit amet luctus venenatis lectus magna. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Enim eu turpis egestas pretium. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Augue lacus viverra vitae congue eu consequat ac felis donec. Sed enim ut sem viverra aliquet eget sit amet. Non sodales neque sodales ut etiam sit amet nisl.

Aliquam faucibus purus in massa tempor nec feugiat. Vitae tempus quam pellentesque nec nam aliquam. Quam pellentesque nec nam aliquam sem et tortor consequat. Mauris rhoncus aenean vel elit scelerisque mauris. At elementum eu facilisis sed odio morbi. Fringilla est ullamcorper eget nulla facilisi. Magnis dis parturient montes nascetur. Vitae congue eu consequat ac. Habitant morbi tristique senectus et netus et malesuada fames ac. Suscipit tellus mauris a diam maecenas sed enim. Est ultricies integer quis auctor elit. Sed felis eget velit aliquet sagittis id. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Fermentum posuere urna nec tincidunt praesent. Lacus sed turpis tincidunt id aliquet risus feugiat. Orci ac auctor augue mauris augue neque gravida in. Praesent elementum facilisis leo vel fringilla.

Pellentesque dignissim enim sit amet venenatis urna cursus eget. Tortor posuere ac ut consequat semper viverra nam libero. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Aliquam sem et tortor consequat id. Id faucibus nisl tincidunt eget. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. At tempor commodo ullamcorper a lacus vestibulum sed. Molestie ac feugiat sed lectus vestibulum mattis. Purus in massa tempor nec. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Volutpat consequat mauris nunc congue nisi vitae suscipit. Amet dictum sit amet justo donec enim diam vulputate ut.

Tristique senectus et netus et malesuada fames ac. Ut porttitor leo a diam sollicitudin tempor id eu. Ligula ullamcorper malesuada proin libero nunc consequat. Aenean vel elit scelerisque mauris pellentesque pulvinar. Non curabitur gravida arcu ac tortor dignissim. Integer quis auctor elit sed vulputate mi sit amet. Suscipit adipiscing bibendum est ultricies integer quis auctor elit. Ultrices gravida dictum fusce ut placerat orci. Urna condimentum mattis pellentesque id. Ultricies mi eget mauris pharetra et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet.

Tortor condimentum lacinia quis vel eros. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Ut faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Lacinia at quis risus sed vulputate odio ut. A iaculis at erat pellentesque adipiscing. Quis enim lobortis scelerisque fermentum dui faucibus. Tristique magna sit amet purus. Posuere lorem ipsum dolor sit amet. Enim eu turpis egestas pretium aenean pharetra magna ac. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Tellus in metus vulputate eu. Pharetra convallis posuere morbi leo. Libero enim sed faucibus turpis in eu mi bibendum neque. Quam lacus suspendisse faucibus interdum posuere. Tempus quam pellentesque nec nam. Pulvinar pellentesque habitant morbi tristique senectus et netus. Amet mauris commodo quis imperdiet massa. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Commodo elit at imperdiet dui accumsan sit amet. At tempor commodo ullamcorper a lacus vestibulum sed."""

for copy in range(1, 6):
    
    trgFile = f'subjects/Text file - {copy}.txt'

    with open(trgFile, 'w', encoding='ascii') as file:
        data = content * copy
        data += data[::-1]
        file.write(data * copy)
        file.close()

